
import { User, Issue, ForumPost, Comment } from './types';

export const users: User[] = [
  {
    id: 1,
    name: 'Anjali Sharma',
    avatar: 'https://i.pravatar.cc/150?u=user1',
    points: 1250,
    district: 'Chennai',
    role: 'citizen',
    badges: [
      { name: 'Active Reporter', icon: 'shield-check', description: 'Reported more than 10 issues.' },
      { name: 'Community Leader', icon: 'star', description: 'Issues have received over 100 upvotes.' },
    ],
  },
  {
    id: 2,
    name: 'Ravi Kumar',
    avatar: 'https://i.pravatar.cc/150?u=user2',
    points: 980,
    district: 'Coimbatore',
    role: 'citizen',
    badges: [
       { name: 'Active Reporter', icon: 'shield-check', description: 'Reported more than 10 issues.' },
    ],
  },
  {
    id: 3,
    name: 'Priya Patel',
    avatar: 'https://i.pravatar.cc/150?u=user3',
    points: 760,
    district: 'Madurai',
    role: 'citizen',
    badges: [],
  },
  {
    id: 4,
    name: 'Suresh Singh',
    avatar: 'https://i.pravatar.cc/150?u=user4',
    points: 1520,
    district: 'Salem',
    role: 'citizen',
    badges: [
      { name: 'Active Reporter', icon: 'shield-check', description: 'Reported more than 10 issues.' },
      { name: 'Community Leader', icon: 'star', description: 'Issues have received over 100 upvotes.' },
      { name: 'Top Contributor', icon: 'trophy', description: 'Ranked #1 on the leaderboard.' },
    ],
  },
  {
    id: 5,
    name: 'Mr. Rajan Gupta',
    avatar: 'https://i.pravatar.cc/150?u=leader1',
    points: 0,
    district: 'Coimbatore',
    panchayat: 'Pollachi',
    role: 'leader',
    email: 'leader@civic.com',
    badges: [],
  }
];

export const currentUser = users[0];

export const mockIssues: Issue[] = [
  {
    id: 1,
    title: 'Large pothole on Main Street',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street near the bus stop. It is causing traffic issues and is a hazard for two-wheelers.',
    category: 'Roads',
    status: 'In Progress',
    upvotes: 128,
    reporterId: 1,
    location: {
      district: 'Coimbatore',
      panchayat: 'Pollachi',
      village: 'Arasampalayam',
      street: 'Main Street',
      lat: 10.7315,
      lng: 77.0125,
    },
    images: ['https://via.placeholder.com/400x300.png/dddddd/000000?text=Pothole+Image+1', 'https://via.placeholder.com/400x300.png/dddddd/000000?text=Pothole+Image+2'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'Critical',
    assignedTo: 'Road Works Team A',
    urgency: 'High',
  },
  {
    id: 2,
    title: 'Garbage not collected for a week',
    description: 'The community garbage bin on Market Road is overflowing. It has not been collected for over a week and is attracting stray animals.',
    category: 'Waste',
    status: 'Received',
    upvotes: 75,
    reporterId: 2,
    location: {
      district: 'Coimbatore',
      panchayat: 'Pollachi',
      village: 'Vellalapalayam',
      street: 'Market Road',
      lat: 10.655,
      lng: 77.032,
    },
    images: ['https://via.placeholder.com/400x300.png/dddddd/000000?text=Garbage+Overflow'],
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'High',
    assignedTo: 'Sanitation Dept.',
    urgency: 'Medium',
  },
  {
    id: 3,
    title: 'Streetlight not working',
    description: 'The streetlight at the corner of Park Avenue and 2nd Cross has been out for three nights, making the area unsafe after dark.',
    category: 'Electricity',
    status: 'Resolved',
    upvotes: 42,
    reporterId: 3,
    location: {
      district: 'Coimbatore',
      panchayat: 'Pollachi',
      village: 'Ayyampalayam',
      street: 'Park Avenue',
      lat: 10.6258,
      lng: 77.0151,
    },
    images: ['https://via.placeholder.com/400x300.png/dddddd/000000?text=Broken+Streetlight'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    resolutionProof: {
      image: 'https://via.placeholder.com/400x300.png/a0e5a0/000000?text=Streetlight+Fixed',
      description: 'The faulty bulb was replaced by the electricity department team.',
      completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    priority: 'Medium',
    assignedTo: 'Electrical Team',
    urgency: 'Medium',
  },
   {
    id: 4,
    title: 'Leaking water pipe',
    description: 'A public water pipe is leaking near the community hall, wasting a lot of water.',
    category: 'Water',
    status: 'Pending',
    upvotes: 91,
    reporterId: 4,
    location: {
      district: 'Coimbatore',
      panchayat: 'Sulur',
      village: 'Kangayampalayam',
      street: 'Community Hall Lane',
      lat: 11.021,
      lng: 77.135,
    },
    images: ['https://via.placeholder.com/400x300.png/dddddd/000000?text=Leaking+Pipe'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'High',
    urgency: 'High',
  },
  {
    id: 5,
    title: 'Broken playground swing',
    description: 'The main swing in the community park is broken and has sharp edges. It is dangerous for children.',
    category: 'Public Infrastructure',
    status: 'Closed',
    upvotes: 65,
    reporterId: 1,
    location: {
      district: 'Coimbatore',
      panchayat: 'Pollachi',
      village: 'Arasampalayam',
      street: 'Central Park',
      lat: 10.7335,
      lng: 77.0145,
    },
    images: ['https://via.placeholder.com/400x300.png/dddddd/000000?text=Broken+Swing'],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    resolutionProof: {
      image: 'https://via.placeholder.com/400x300.png/a0e5a0/000000?text=Swing+Repaired',
      description: 'The swing was removed and a new one has been installed.',
      completedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    closedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'Medium',
    assignedTo: 'Park Maintenance',
    urgency: 'High',
  },
];

export const mockForumPosts: ForumPost[] = [
    {
        id: 101,
        authorId: 2,
        title: "Ideas for a community garden in our village?",
        content: "I've noticed an unused plot of land near the old temple. I was thinking it would be a great spot for a community garden where we can grow our own vegetables. What does everyone think? We could approach the Panchayat with a plan if there's enough interest.",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 102,
        authorId: 4,
        title: "Weekly cleanup drive organization",
        content: "The amount of litter on the main roads is increasing. I suggest we organize a voluntary cleanup drive every Sunday morning. We can focus on one street each week. Who would be willing to join? We'll need to coordinate for supplies like gloves and bags.",
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 103,
        authorId: 1,
        title: "Request for better bus frequency",
        content: "The bus service to the main city is very infrequent, especially in the evenings. This makes it difficult for students and people working late. Should we draft a joint petition to the transport authorities? We can collect signatures and submit it.",
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

export const mockComments: Comment[] = [
    {
        id: 201,
        postId: 101,
        authorId: 3,
        content: "This is a wonderful idea, Ravi! My family would love to participate. I have some experience with gardening and can help.",
        createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
        upvotes: 15,
    },
    {
        id: 202,
        postId: 101,
        authorId: 1,
        content: "I agree! A community garden would be fantastic for our village. We should check who owns the land first.",
        createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        upvotes: 8,
    },
    {
        id: 203,
        postId: 102,
        authorId: 2,
        content: "Count me in for the cleanup drive. Great initiative, Suresh!",
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        upvotes: 12,
    },
    {
        id: 204,
        postId: 103,
        authorId: 4,
        content: "Yes, the bus service is a real problem. A petition is a good first step. I can help draft it.",
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        upvotes: 22,
    },
    {
        id: 205,
        postId: 101,
        authorId: 4,
        content: "I spoke to my uncle who works in the land records office. He said the plot belongs to the Panchayat, so it should be possible to get permission.",
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        upvotes: 10,
    },
];
